name: Conformance Tests

on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:

jobs:
  conformance:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b # v5.3.0
        with:
          python-version: "3.x"
          cache: "pip"
          cache-dependency-path: pyproject.toml

      - name: install sigstore-python
        run: python -m pip install .

      - uses: sigstore/sigstore-conformance@b0635d4101f11dbd18a50936568a1f7f55b17760 # v0.0.14
        with:
          entrypoint: ${{ github.workspace }}/test/integration/sigstore-python-conformance
          xfail: "test_verify_with_trust_root test_verify_dsse_bundle_with_trust_root" # see issue 821
