name: Conformance Tests

on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:

jobs:
  conformance:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2

      - uses: actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c # v5.0.0
        with:
          python-version: "3.x"
          cache: "pip"
          cache-dependency-path: pyproject.toml

      - name: install sigstore-python
        run: python -m pip install .

      - uses: sigstore/sigstore-conformance@ee4de0e602873beed74cf9e49d5332529fe69bf6 # v0.0.11
        with:
          entrypoint: ${{ github.workspace }}/test/integration/sigstore-python-conformance
          xfail: "test_verify_with_trust_root test_verify_dsse_bundle_with_trust_root" # see issue 821
